-- ===========================================================================
-- Phase 3 / Task 0.6: Add `many_to_one` to the relationship_type enum
-- ===========================================================================
--
-- The CRM relationships (contact→account, opportunity→account,
-- opportunity→contact) are all many-to-one when stored with the "many"
-- side as the source and the "one" side as the target — the orientation
-- the Phase 3 plan's query examples assume
-- ("all opportunities for account X": source_record_id = opportunity,
-- target_record_id = account).
--
-- The original enum only had one_to_one / one_to_many / many_to_many, so
-- there was no faithful value for that orientation. Rather than invert
-- source/target (which would diverge from the documented query
-- convention), we add the missing value — "fix the framework, not the
-- module".
--
-- Idempotent: ADD VALUE IF NOT EXISTS. Safe to re-run.
--
-- NOTE: ALTER TYPE ... ADD VALUE cannot run inside a transaction block,
-- and a newly added value cannot be used in the same transaction it was
-- added in. Apply this once, standalone, before any code that inserts
-- 'many_to_one' relationship rows (tests included).
--
-- Apply locally:
--   psql "postgresql://jamesfoley@localhost:5432/adserve" -v ON_ERROR_STOP=1 \
--     -f packages/database/sql/004-add-many-to-one-relationship-type.sql
--   (or: pnpm db:push — drizzle-kit picks up the enum change)
-- Apply on RDS (deferred, same pattern as 003):
--   psql "$DATABASE_URL_MIGRATOR" -v ON_ERROR_STOP=1 \
--     -f packages/database/sql/004-add-many-to-one-relationship-type.sql
-- ===========================================================================

ALTER TYPE relationship_type ADD VALUE IF NOT EXISTS 'many_to_one' AFTER 'one_to_many';
